name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ rakshithadn1234 }}
        password: ${{ nasunara1234 }}

    - name: Build Docker image
      run: docker build -t your-docker-username/your-repo-name:${{ github.sha }} .

    - name: Push Docker image
      run: docker push your-docker-username/your-repo-name:${{ github.sha }}
