name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Load Docker Hub credentials from docker.env
      run: |
        source docker.env
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      shell: bash

    - name: Build Docker image
      run: docker build -t rakshithadn1234/nasunara1234:${{ github.sha }} .

    - name: Push Docker image
      run: docker push rakshithadn1234/nasunara1234:${{ github.sha }}
